# Generated by Django 4.2.6 on 2023-10-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellpetdb',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
