# Generated by Django 4.2.6 on 2023-11-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0004_sellersignupdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sellersignupdb',
            new_name='sellersigndb',
        ),
    ]
