# Generated by Django 4.2.6 on 2023-11-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0005_rename_sellersignupdb_sellersigndb'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersigndb',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
