# Generated by Django 4.2.6 on 2023-11-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0006_sellersigndb_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sellersigndb',
        ),
    ]
