# Generated by Django 4.2.6 on 2023-11-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0007_delete_sellersigndb'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellersigndb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(blank=True, max_length=50, null=True)),
                ('pswrd', models.CharField(blank=True, max_length=50, null=True)),
                ('re_pswrd', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
