# Generated by Django 4.2.6 on 2023-11-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0008_sellersigndb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellersigndb',
            old_name='pswrd',
            new_name='paswrd',
        ),
        migrations.RenameField(
            model_name='sellersigndb',
            old_name='uname',
            new_name='sname',
        ),
    ]
