# Generated by Django 4.2.6 on 2023-11-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0009_rename_pswrd_sellersigndb_paswrd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellpetdb',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
