# Generated by Django 4.2.6 on 2023-12-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='backendsigndb',
        ),
    ]
