# Generated by Django 4.2.6 on 2023-11-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_reviewdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewdb',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
