# Generated by Django 4.2.6 on 2023-11-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_alter_reviewdb_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdb',
            name='item',
        ),
        migrations.RemoveField(
            model_name='reviewdb',
            name='user',
        ),
        migrations.AddField(
            model_name='reviewdb',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reviewdb',
            name='uname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
