# Generated by Django 4.2.6 on 2023-12-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0012_buypagedb_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buypagedb',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='buypagedb',
            name='name',
        ),
    ]
