# Generated by Django 4.2.6 on 2023-12-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0015_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
