# Generated by Django 4.2.6 on 2023-12-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0016_remove_message_room_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='fimg',
            field=models.ImageField(blank=True, null=True, upload_to='food_img'),
        ),
    ]
