# Generated by Django 4.2.6 on 2023-12-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0019_sellerpetdb_selleremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificationdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selleremail', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('breed', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('uname', models.CharField(blank=True, max_length=50, null=True)),
                ('petimg', models.ImageField(blank=True, null=True, upload_to='pet_img')),
            ],
        ),
    ]
