# Generated by Django 4.2.6 on 2023-12-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0020_notificationdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationdb',
            name='petimg',
        ),
    ]
