# Generated by Django 4.2.6 on 2023-12-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0023_signupdb_mob'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdb',
            name='mob',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
