# Generated by Django 4.2.6 on 2023-12-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0024_notificationdb_mob'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminnotificationdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aemail', models.CharField(blank=True, max_length=50, null=True)),
                ('amob', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('breed', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('uname', models.CharField(blank=True, max_length=50, null=True)),
                ('mob', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
