# Generated by Django 4.2.6 on 2023-12-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0025_adminnotificationdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('msg', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
